### PR TITLE
David/test setup

### PR DESCRIPTION
**Pull request by lmy0125**
Added Jest and Testing Library, and created basic tests for index.js and FirstTimeUser.js.
Created a sample friends page for future use.

### CODE REVIEW

**Comment by lmy0125** [comment]
Having some errors in the client console, which won't affect how the UI looks. Need to fix those after the meeting tomorrow.

**Comment by lmy0125** [comment]
Updated and styled properties and roommates page.

**Comment by jn1118** [comment]
Highly suggest to put different content into separate PRs for easier review and avoid dependency issue.

**Comment by lmy0125** [comment]
Trying to split this PR.

**Review by jn1118 — APPROVED** [review]
LGTM

**Pull request merged**
