### PR TITLE
feat: load other user data from backend

### LINKED ISSUE #59: Fetch other user's data for userProfile page

### PR DESCRIPTION
**Pull request by aidandenlinger**
#61 is merged and this is ready for review.

~~**Relies on #61 being merged, leaving as draft until then.** I built off of #61 so some details in the diff are only there because they're from #61. Once #61 is merged I'll rebase and the diff will be more accurate.~~

Closes #59. 

- Loads user data from backend to display on profile page. Access profiles by clicking on "view profile" from the roommates page.
- Hides property carousels if user being viewed has no property liked.
- Clickable contact info row that links directly to websites, also more reactive than before on screen size.
- Page can handle certain fields not being filled out for the header, for example not having a bio does not leave an empty space.

## Future Work: Integrate Property Data
- Add property cards, right now if user does have interested properties it just displays the property UID ([see example here](https://roomie-hqqs9xog4-cse210-g13.vercel.app/user/PQR456)). Wanted to keep this PR focused solely on tying in backend before working on frontend stuff, but that will be a very soon separate PR.
- Get the union of logged in user liked properties and the user we're viewing. Running into async issues where I need to get the user id of the currently logged in user (sync code) then get the properties they like (async code)

### CODE REVIEW

**Comment by aidandenlinger** [comment]
discord does not allow for links directly to profiles, I just link to discord.com as a lame alternative

**Comment by aidandenlinger** [comment]
Some users are broken until the firebase user data is fixed - there are users who share the same ID, if you click any of those users you may get someone else's profile (since you click on the button, it requests user "XYZ789", but since there are 4 users with that ID you may not get the user you clicked on)

**Comment by bjtrieu** [comment]
> discord does not allow for links directly to profiles, I just link to discord.com as a lame alternative. this wouldn't be resolved by asking for urls instead - there literally is no url discord provides that you can click on to view a profile, you _have_ to search them up from the app. please let me know if i missed some info because i'd love to resolve this

looks like there _are_ links but that requires getting the uid which we don't have access to so I think what you have works
https://www.itgeared.com/how-to-share-discord-profile-link/

**Review by bjtrieu — COMMENTED** [review]
everything looks good. just to note from discussion on discord:

- we're going to upload the user data to "users"
- user IDs in the database are being fixed right now so will review again once those have been uploaded

**Comment by aidandenlinger** [comment]
With the users db fixed this is ready for merge! Since none of the users in the database have liked properties, none of them will have a carousel - this is by design, the carousel is not shown when a user has no liked properties.. When I work on the property frontend I'll add some property likes to test it out.

**Review by bjtrieu — APPROVED** [review]
lgtm

**Pull request merged**
